name: CI NestJS API

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    name: Instalar, probar y push a Docker Hub
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Instalar dependencias y correr tests
        run: |
          npm ci
          npm run test:ci

      - name: Build Docker image
        run: |
          docker build \
            --file Dockerfile \
            --tag "${{ secrets.DOCKERHUB_USERNAME }}/pagos-api:${{ github.sha }}" .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker tag "${{ secrets.DOCKERHUB_USERNAME }}/pagos-api:${{ github.sha }}" \
                     "${{ secrets.DOCKERHUB_USERNAME }}/pagos-api:latest"
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/pagos-api:${{ github.sha }}"
          docker push "${{ secrets.DOCKERHUB_USERNAME }}/pagos-api:latest"
